/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentation;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naesh619
 */
public class EditSolution extends javax.swing.JFrame {
    
    ViewController vc;
    /**
     * Creates new form EditSolution
     */
    public EditSolution(ViewController vc) {
        initComponents();
        this.vc = vc;
        
        actTables();
    }
    
    private void actTables(){
        DefaultTableModel model =  (DefaultTableModel) nodesTable.getModel();
        DefaultTableModel model2 =  (DefaultTableModel) nodesTable2.getModel();
        while(model.getRowCount()>0)model.removeRow(0);
        while(model2.getRowCount()>0)model2.removeRow(0);
        
        for (int i = 0; i < vc.getSolutionString().size(); i++) {
            model.addRow(new Object[] {vc.getSolutionString().get(i)});
            model2.addRow(new Object[] {vc.getSolutionString().get(i)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        nodesTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        nodesTable2 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(450, 320));

        editButton.setText("Edit");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });

        nodesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Node1"
            }
        ));
        nodesTable.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(nodesTable);
        nodesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        nodesTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Node2"
            }
        ));
        jScrollPane1.setViewportView(nodesTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton)
                .addGap(103, 103, 103))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        // TODO add your handling code here:
        String s1,s2;
        int pos1 = nodesTable.getSelectedRow();
        int pos2 = nodesTable2.getSelectedRow();
        if (pos1 != -1 && pos2 != -1){
            DefaultTableModel model =  (DefaultTableModel) nodesTable.getModel();
            DefaultTableModel model2 =  (DefaultTableModel) nodesTable2.getModel();
            
            Object valueAt = model.getValueAt(pos1, 0);
            Object valueAt2 = model2.getValueAt(pos2, 0);
            
            s1 = (String) valueAt;
            s2 = (String) valueAt2;
            
            s1 = s1.trim();
            s2 = s2.trim();
            
            if (!(s1.equals("") || s2.equals(""))){
                System.out.println("s1: "+s1+"\ns2: "+s2);
                vc.modifySolution(s1,s2);
                actTables();
            }
            else JOptionPane.showConfirmDialog(null, "2 rows must be selected", "ERROR:", JOptionPane.OK_CANCEL_OPTION);
        }
        else JOptionPane.showConfirmDialog(null, "2 rows must be selected", "ERROR:", JOptionPane.OK_CANCEL_OPTION);
    }//GEN-LAST:event_editButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable nodesTable;
    private javax.swing.JTable nodesTable2;
    // End of variables declaration//GEN-END:variables
}
