/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentation;

import exceptions.PacketException;
import java.awt.Color;
import java.awt.Graphics2D;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author adria.manes.medina
 */
public class Frame extends javax.swing.JFrame {
    
    ViewController vc;

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        vc = new ViewController();
        vc.loadMap();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        addPacketLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        addPacketButton = new javax.swing.JButton();
        idStaticLabel = new javax.swing.JLabel();
        editDelPacketLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        addressLabel2 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        addressText2 = new javax.swing.JTextField();
        deletePacketButton = new javax.swing.JButton();
        editPacketButton = new javax.swing.JButton();
        idOutLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        calculateRouteButton = new javax.swing.JButton();
        showRouteButton = new javax.swing.JButton();
        editRouteButton = new javax.swing.JButton();
        routeText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fast = new javax.swing.JCheckBox();
        optim = new javax.swing.JCheckBox();
        mapDrawPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        importMenu = new javax.swing.JMenu();
        mapImportMenu = new javax.swing.JMenuItem();
        packetListImportMenu = new javax.swing.JMenuItem();
        exportMenu = new javax.swing.JMenu();
        routeExportMenu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        editDistances = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        addPacketLabel.setText("Add New Packet:");

        addressLabel.setText("Address:");

        addPacketButton.setText("Add Packet");
        addPacketButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPacketButtonMouseClicked(evt);
            }
        });
        addPacketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPacketButtonActionPerformed(evt);
            }
        });

        idStaticLabel.setText("ID:");

        editDelPacketLabel.setText("Edit/Delete Packet:");

        idLabel.setText("ID:");

        addressLabel2.setText("Address:");

        deletePacketButton.setText("Delete");
        deletePacketButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletePacketButtonMouseClicked(evt);
            }
        });
        deletePacketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePacketButtonActionPerformed(evt);
            }
        });

        editPacketButton.setText("Edit");
        editPacketButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPacketButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addPacketLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idStaticLabel)
                                    .addComponent(addressLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idOutLabel)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(addPacketButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editDelPacketLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressLabel2)
                                    .addComponent(idLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idText)
                                    .addComponent(addressText2))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deletePacketButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editPacketButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPacketLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idStaticLabel)
                    .addComponent(idOutLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addPacketButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editDelPacketLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel2)
                    .addComponent(addressText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePacketButton)
                    .addComponent(editPacketButton))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        calculateRouteButton.setText("Calculate");
        calculateRouteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateRouteButtonMouseClicked(evt);
            }
        });

        showRouteButton.setText("Show");
        showRouteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showRouteButtonMouseClicked(evt);
            }
        });
        showRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRouteButtonActionPerformed(evt);
            }
        });

        editRouteButton.setText("Edit");
        editRouteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editRouteButtonMouseClicked(evt);
            }
        });

        jLabel4.setText("Route");

        fast.setSelected(true);
        fast.setText("Fast");
        fast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastActionPerformed(evt);
            }
        });

        optim.setText("Optim");
        optim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(362, 715, Short.MAX_VALUE)
                .addComponent(editRouteButton)
                .addGap(157, 157, 157))
            .addComponent(routeText, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fast)
                            .addComponent(optim))
                        .addGap(57, 57, 57)
                        .addComponent(calculateRouteButton)
                        .addGap(140, 140, 140)
                        .addComponent(showRouteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(routeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(fast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editRouteButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(optim)
                        .addComponent(calculateRouteButton)
                        .addComponent(showRouteButton)))
                .addContainerGap())
        );

        mapDrawPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mapDrawPanelLayout = new javax.swing.GroupLayout(mapDrawPanel);
        mapDrawPanel.setLayout(mapDrawPanelLayout);
        mapDrawPanelLayout.setHorizontalGroup(
            mapDrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mapDrawPanelLayout.setVerticalGroup(
            mapDrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        fileMenu.setText("File");

        importMenu.setText("Import");

        mapImportMenu.setText("Map");
        mapImportMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapImportMenuMouseClicked(evt);
            }
        });
        mapImportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapImportMenuActionPerformed(evt);
            }
        });
        importMenu.add(mapImportMenu);

        packetListImportMenu.setText("Packet List");
        packetListImportMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packetListImportMenuMouseClicked(evt);
            }
        });
        packetListImportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packetListImportMenuActionPerformed(evt);
            }
        });
        importMenu.add(packetListImportMenu);

        fileMenu.add(importMenu);

        exportMenu.setText("Export");

        routeExportMenu.setText("Route");
        routeExportMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                routeExportMenuMouseClicked(evt);
            }
        });
        routeExportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeExportMenuActionPerformed(evt);
            }
        });
        exportMenu.add(routeExportMenu);

        fileMenu.add(exportMenu);

        jMenuBar1.add(fileMenu);

        jMenu5.setText("Map");

        editDistances.setText("Edit Distances");
        editDistances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDistancesActionPerformed(evt);
            }
        });
        jMenu5.add(editDistances);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mapDrawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapDrawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletePacketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePacketButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletePacketButtonActionPerformed

    private void showRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRouteButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_showRouteButtonActionPerformed

    private void showRouteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showRouteButtonMouseClicked
        try {
            // TODO add your handling code here:
            DrawTSP.DrawMap(vc,mapDrawPanel);
           // System.out.println("Es fa la crida desde frame");
        } catch (Exception ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(null, ex.getMessage(), "Error", JOptionPane.OK_CANCEL_OPTION);
        }
        
    }//GEN-LAST:event_showRouteButtonMouseClicked

    private void addPacketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPacketButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPacketButtonActionPerformed

    private void addPacketButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPacketButtonMouseClicked
        // TODO add your handling code here:        
        idOutLabel.setText(vc.addPacket(addressText.getText()).toString());
    }//GEN-LAST:event_addPacketButtonMouseClicked

    private void deletePacketButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePacketButtonMouseClicked
        // TODO add your handling code here:
        vc.deletePacket(Integer.parseInt(idText.getText()));
    }//GEN-LAST:event_deletePacketButtonMouseClicked

    private void editPacketButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPacketButtonMouseClicked
        // TODO add your handling code here:
        vc.setPacket(Integer.parseInt(idText.getText()), addressText2.getText());
    }//GEN-LAST:event_editPacketButtonMouseClicked

    private void calculateRouteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateRouteButtonMouseClicked
        // TODO add your handling code here:
        if(fast.isSelected())vc.runAlgorithm(1);
        else vc.runAlgorithm(2);
        routeText.setText(vc.getSolutionString().toString());
        
    }//GEN-LAST:event_calculateRouteButtonMouseClicked

    private void mapImportMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapImportMenuMouseClicked
        // TODO add your handling code here:
        vc.loadMap();
        System.out.print("clicked");
    }//GEN-LAST:event_mapImportMenuMouseClicked

    private void packetListImportMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packetListImportMenuMouseClicked
        // TODO add your handling code here:
        vc.loadPacketSet();
    }//GEN-LAST:event_packetListImportMenuMouseClicked

    private void routeExportMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routeExportMenuMouseClicked
        // TODO add your handling code here:
        vc.saveSolution();
    }//GEN-LAST:event_routeExportMenuMouseClicked

    private void mapImportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapImportMenuActionPerformed
        // TODO add your handling code here:
        vc.loadMap();
    }//GEN-LAST:event_mapImportMenuActionPerformed

    private void packetListImportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packetListImportMenuActionPerformed
        // TODO add your handling code here:
        vc.loadPacketSet();
    }//GEN-LAST:event_packetListImportMenuActionPerformed

    private void routeExportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeExportMenuActionPerformed
        // TODO add your handling code here:
        vc.saveSolution();
    }//GEN-LAST:event_routeExportMenuActionPerformed

    private void editDistancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDistancesActionPerformed
        // TODO add your handling code here:
        EditDistances ed = new EditDistances(vc);
        ed.setVisible(true);
        
    }//GEN-LAST:event_editDistancesActionPerformed

    private void fastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastActionPerformed
        // TODO add your handling code here:
        if(fast.isSelected()) optim.setSelected(false);
    }//GEN-LAST:event_fastActionPerformed

    private void optimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optimActionPerformed
        // TODO add your handling code here:
        if(optim.isSelected()) fast.setSelected(false);
    }//GEN-LAST:event_optimActionPerformed

    private void editRouteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editRouteButtonMouseClicked
        // TODO add your handling code here:
        EditSolution es = new EditSolution(vc);
        es.setVisible(true);
    }//GEN-LAST:event_editRouteButtonMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPacketButton;
    private javax.swing.JLabel addPacketLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField addressText2;
    private javax.swing.JButton calculateRouteButton;
    private javax.swing.JButton deletePacketButton;
    private javax.swing.JLabel editDelPacketLabel;
    private javax.swing.JMenuItem editDistances;
    private javax.swing.JButton editPacketButton;
    private javax.swing.JButton editRouteButton;
    private javax.swing.JMenu exportMenu;
    private javax.swing.JCheckBox fast;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idOutLabel;
    private javax.swing.JLabel idStaticLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JMenu importMenu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPanel mapDrawPanel;
    private javax.swing.JMenuItem mapImportMenu;
    private javax.swing.JCheckBox optim;
    private javax.swing.JMenuItem packetListImportMenu;
    private javax.swing.JMenuItem routeExportMenu;
    private javax.swing.JTextField routeText;
    private javax.swing.JButton showRouteButton;
    // End of variables declaration//GEN-END:variables
}
